autohome:
  job:
    mustBeExecuted: true
    admin:
      addresses: http://jobadmin.yz.test.autohome.com.cn
    accessToken: d7fe12b33d4c1a5423feb137e6b7bcd3

kafkatopics: autohome_data_transit

#spring:
#  elasticsearch:
#    uris: lf-test-es79.search.corpautohome.com
#    port: 80
#    username: autotest
#    password: 4R16vKlFMYZEltuZ4YaC
#  elasticsearch2:
#    uris: lf-appes-es68.search.hera.corpautohome.com
#    port: 80